refactor: reuse timeout channel creation
andreev-io/little-raft pull request #27
Opened 2021-12-16 06:15 UTC by suzaku

2021-12-16 06:17 UTC, penberg approved these changes
lgtm!

2021-12-16 11:13 UTC, fzyzcjy approved these changes

2021-12-16 11:13 UTC, fzyzcjy commented
oops please ignore my approval (mistakenly click that)

2021-12-16 12:05 UTC, andreev-io requested changes

2021-12-16 12:05 UTC, andreev-io commented on little_raft/src/timer.rs
> +fn get_timeout_channel(timeout: Duration) -> Receiver<()> {
Let's move this function into `impl Timer` and just keep it private and call it with `Timer::get_timeout_channel(self.timeout)`.

2021-12-17 09:06 UTC, andreev-io approved these changes

2021-12-17 09:08 UTC, merged

2021-12-17 09:09 UTC, andreev-io commented
Congrats on your first contribution to Little Raft, @suzaku!

2021-12-17 09:10 UTC, suzaku commented
> Congrats on your first contribution to Little Raft, @suzaku!

Let's hope it's not the only one. I code in Go and Python mostly, but I'm practicing with Rust lately, if you have some easy to pick up issues, please let me know.