fix #13, Add Abandoned type to TransitionState enum
andreev-io/little-raft pull request #33
Opened 2021-12-17 09:50 UTC by suzaku

2021-12-17 10:45 UTC, penberg commented on little_raft/src/state_machine.rs
> +    // NotLeader transitions have been abandoned because the replica is not the cluster leadedr.
s/leadedr/leader/

2021-12-17 21:06 UTC, andreev-io requested changes

2021-12-17 21:06 UTC, andreev-io commented on little_raft/src/replica.rs
> +            } else {
Looks good to me. Little Raft is single-threaded, so we don't have to worry about state changing under our feet, so let's move the Leader check on line 369 here out of the `for` loop for efficiency just like you did in the previous draft PR.

And then let's reuse `let mut state_machine` declaration by declaring the variable outside the `if` statement.

2021-12-17 21:06 UTC, andreev-io commented on little_raft/src/state_machine.rs
> +    // NotLeader transitions have been abandoned because the replica is not the cluster leadedr.
Let's also keep comment width at 80 characters please.

2021-12-18 02:29 UTC, suzaku commented
@andreev-io Updated.

2021-12-18 05:54 UTC, penberg commented
Looks good. Is this in draft mode on purpose, @suzaku, or can this be merged?

2021-12-18 06:04 UTC, suzaku commented
> Looks good. Is this in draft mode on purpose, @suzaku, or can this be merged?

I would like to add a test case for this, but maybe we can do that in another PR if you don't mind.

2021-12-18 06:43 UTC, penberg approved these changes

2021-12-18 09:25 UTC, andreev-io approved these changes

2021-12-18 09:27 UTC, merged